name: k8s-slackbot
version: 0.0.1
home: "https://github.com/tracing-app/backend"
maintainers:
  - name: "Amrit Baveja"
    email: "amrit_baveja@branson.org"
dependencies:
  - name: botkube
    version: "v0.11.0"
    repository: "https://infracloudio.github.io/charts"